#!/usr/bin/env perl

use strict;
use warnings;
use feature qw( say );
use DBI;
use Getopt::Std qw( getopts );

sub print_rows {
  my $sth = shift;

  while ( my $hashref = $sth->fetchrow_hashref ) {
    my $id               = $hashref->{ID};
    my $vendor           = $hashref->{VENDOR};
    my $model_number     = $hashref->{MODEL_NUMBER};
    my $serial_number    = $hashref->{SERIAL_NUMBER};
    my $warranty_expires = $hashref->{WE} // '';

    my $message = sprintf '%2d  %-18s  %-23s  %-18s  %s', $id, $vendor, $model_number, $serial_number, $warranty_expires;
    say $message;
  }
}

sub list {
  my $dbh = shift;

  my $sth = $dbh->prepare( 'SELECT ID, VENDOR, MODEL_NUMBER, SERIAL_NUMBER, TO_CHAR( WARRANTY_EXPIRES, \'YYYY-MM-DD\' ) WE FROM DRIVES ORDER BY ID' );
  $sth->execute;

  &print_rows( $sth );

  $sth->finish;
}

sub search {
  my ( $dbh, $query, $field ) = @_;

  if ( not defined $query ) {
    say STDERR 'query must be specified';
    return;
  }

  unless ( defined $field ) {
    $field = ( $query =~ m/\A\d+\Z/ ) ? 'ID' : 'SERIAL_NUMBER';
  }

  my $sql = sprintf 'SELECT ID, VENDOR, MODEL_NUMBER, SERIAL_NUMBER, TO_CHAR( WARRANTY_EXPIRES, \'YYYY-MM-DD\' ) WE FROM DRIVES WHERE %s = %s ORDER BY ID', $field, $dbh->quote( $query );
  my $sth = $dbh->prepare( $sql );
  $sth->execute;

  &print_rows( $sth );

  $sth->finish;
}

sub add {
  my ( $dbh, $vendor, $model_number, $serial_number, $warranty_expires ) = @_;

  if ( not defined $vendor or not defined $model_number or not defined $serial_number ) {
    say STDERR 'vendor, model_number and serial_number must be specified';
    return;
  }

  my $sth = $dbh->prepare( 'INSERT INTO DRIVES ( VENDOR, MODEL_NUMBER, SERIAL_NUMBER, WARRANTY_EXPIRES ) VALUES ( ?, ?, ?, TO_DATE( ?, \'YYYY-MM-DD\' ) )' );
  $sth->execute( $vendor, $model_number, $serial_number, $warranty_expires );
  $sth->finish;
}

sub delete {
  my ( $dbh, $id ) = @_;

  if ( not defined $id ) {
    say STDERR 'id must be specified';
    return;
  }

  my $sth = $dbh->prepare( 'DELETE FROM DRIVES WHERE ID = ?' );
  $sth->execute( $id );
  $sth->finish;
}

my %dispatch_table = ( list   => \&list,
                       l      => \&list,
                       search => \&search,
                       s      => \&search,
                       add    => \&add,
                       a      => \&add,
                       delete => \&delete,
                       d      => \&delete );

my %opts;
getopts( 'd:u:p:', \%opts );
my $db       = $opts{d};
my $user     = $opts{u};
my $password = $opts{p};

if ( not defined $db or not defined $user or not defined $password ) {
  say STDERR 'db(-d), user(-u) and password(-p) must be specified';
  exit -1;
}

my $dbh = DBI->connect( "dbi:Oracle:$db", $user, $password ) or die $!;

my $command = ( @ARGV < 1 ) ? 'list' : shift;
if ( exists $dispatch_table{$command} ) {
  $dispatch_table{$command}->( $dbh, @ARGV );
}

$dbh->disconnect;

exit 0;
